USE u234111db1;

INSERT INTO department (name)
VALUES ('Informationstechnologie'),
       ('FS Informationstechnik'),
       ('Mechatronik'),
       ('Allgemein');

INSERT INTO achievement (name, fk_departmentID, description)
VALUES ('Willkommen', 4, 'Willkommen an der HTL Rennweg. Wir hoffen Sie haben einen informativen Tag!'),
       ('Wissenschaftler', 4,
        'Hier lernt man viel über Physik und Chemie. Verbunden mit interessanten Experimenten kann man auch in Naturwissenschaften (Physik und Chemie) maturieren.'),
       ('Auf Wiedersehen', 4, 'Auf Wiedersehen! Wir hoffen Sie hatten einen großartigen Tag an unserer Schule.'),
       ('Zauberlehrling', 1,
        'Hier zeigt Prof. Zainzinger einen vermeintlichen Zaubertrick. Tatsächlich ist es jedoch einfache Informatik'),
       ('Hör-Test', 1,
        'In diesem Labor lernt man viel über Akustik, digitale Audiosignale, Effekte, Lautsprecher, Mikros…'),
       ('Smile!', 1,
        'Hier erlernt man sowohl das Fotografieren als auch die Bearbeitung von Bildern. Außerdem erfährt man, was noch alles dazugehört, wie z.B. die richtige Belichtung eines Sets.'),
       ('3…2…1…Action', 1,
        'Das Videolabor ist der richtige Ort, wenn man sich schon mal gefragt hat, wie ein Film gemacht wird.'),
       ('Spielwiese', 1,
        'In diesem Raum sind viele Kabel, die das Internet in dieser Schule tragen. Wie das funktioniert, lernt man in Netzwerktechnik.'),
       ('Lasertech', 3,
        'Light Amplification by Stimulated Emission of Radiation oder auf Deutsch: Licht-Verstärkung durch stimulierte Emission von Strahlung. Wenn das verwirrend klingt, dann ist das voll ok – hier erfährt man mehr. '),
       ('I\'ll be back', 3,
        'Hier erfährt man wie man Maschinenbau und Elektrotechnik vereint und, wie der Name schon sagt, die Vorgänge in Maschinen, Anlagen und technischen Systemen zu automatisieren.'),
       ('3D Experte', 3,
        'Hier lernt man viel über das 3D-Modellieren von Objekten. Auch wie man mit einem 3D-Drucker umgeht, ist hier Teil des Unterrichts.'),
       ('Bills Geschenk', 3,
        'Selbst die kleinsten Prozessoren werden hergestellt. Wie das funktioniert, lernt man hier.'),
       ('Meister Schmied', 3,
        'Stahl ist ein sehr hartes Material. Die Verwertung und Verwendung davon ist ein wichtiger Teil unserer Wirtschaft. Wenn du dich fragst, wie das funktioniert, dann wirst du hier Antworten bekommen.'),
       ('Medienprofi', 2,
        'Diese Projekte sind ein guter Einblick, was man in der Fachschule in der Medientechnik lernt.'),
       ('Kabel-Action', 2,
        'Diese Projekte sind ein guter Einblick, was man in der Fachschule in der Netzwerktechnik lernt.'),
       ('The End?', 2,
        'Hier lassen sich die Abschlussarbeiten der Fachschüler finden. Ihr letztes Projekt bevor es in die Berufswelt gehen.');

INSERT INTO location (roomNumber, name)
VALUES ('LIZ (120)', 'Lern- und Informationszentrum'),
       ('PH (157)', 'Physiksaal'),
       ('CH (161)', 'Chemiesaal'),
       ('000', 'Aula'),
       ('L.NW.0 (061)', 'Labor Netzwerktechnik 0'),
       ('054', 'Labor Audio'),
       ('E.9 (245)', 'EDV 9'),
       ('L.A (059)', 'Labor Video'),
       ('L.NW.C (076)', 'Labor-Cisco'),
       ('W.123', 'Werkstätte Montage'),
       ('L.AUT (075)', 'Labor Automatisierungstechnik'),
       ('179', '3D Konstruktion'),
       ('L.MP (056)', 'Labor Mikroprozessoren'),
       ('W.119', 'Werkstätte Stahlbau'),
       ('E.7 (235)', 'EDV 7'),
       ('L.NW.2 (072)', 'Labor Netzwerktechnik 2'),
       ('E.8 (243)', 'EDV 8');

INSERT INTO achievementAtLocation (fk_achievementID, fk_locationID)
VALUES (1, 1),
       (2, 2),
       (2, 3),
       (3, 4),
       (4, 5),
       (5, 6),
       (6, 7),
       (7, 8),
       (8, 9),
       (9, 10),
       (10, 11),
       (11, 12),
       (12, 13),
       (13, 14),
       (14, 15),
       (15, 16),
       (15, 17);